---
title: "Excess death in Mexico City and us"
author: "Dan Weinberger"
date: "10/17/2020"
output:
  html_document:
    df_print: paged
    html_document: null
    toc: yes
    toc_depth: 2
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '2'
  pdf_document: 
    keep_tex:  true
params:
  agg.level: 'state'
  n.days.filter: 20
  web.version: FALSE
  extrap.date: '2020-01-26'
  count.start.date: '2020-03-01'
  end.data.date: '2020-09-05'
---

```{r, include = F}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo=F,
  warning=FALSE, 
  message=FALSE,
  comment = "#>",
  dev=c('png','pdf'),
  fig.path='./figures/',
  gganimate = list(
    nframes = 50)
)

extrap.date <-  as.Date(params$extrap.date)
count.start.date <- as.Date(params$count.start.date)
end.data.date <- as.Date(params$end.data.date)

state.name2 <- c(state.name, 'District of Columbia','Puerto Rico', 'United States', 'New York City')
state.abb2 <- c(state.abb, 'DC','PR','US','us')


last.date.format <- 
  format(end.data.date, '%b %d, %Y')
```

```{r setup}
library(ExcessILI)
library(readxl)
library(cdcfluview)
library(reshape2)
library(ggplot2)
library(lubridate)
library(RColorBrewer)
library(plotly)
library(MMWRweek)
library(readr)
library(rjson)
library(htmlTable)
library(RSocrata)
library(pdftools)
library(readr)
library(abind)
library(gsubfn)
library(dplyr)
library(RCurl)
library(gifski)
library(gganimate)
#library(jsonlite)
set.seed(123)
source('./functions/ts_plot_func.R')
source('./functions/format_table.R')
source('./functions/stack_plot.R')

```

```{r archivfunc}
# Using ExcessILI's data archiving functions, returns the most recent copy of
# output obtained by running a function or formula \code{f}, unless this 
# copy doesn't exist or is older (by modification time) than \code{maxage}.
# In that case, \code{f} is run and the output is archived into the folder
# Data/'storeName' as an RDS file, using the function ExcessILI::storeRDS.
#
# @param storeName A string. The name of the folder to store output in
# @param f A function or formula taking no arguments. Formulas are coerced to
#   functions.
# @param maxage How old can any existing archived file be before \code{f} is 
#   called again?
runIfExpired <- function(storeName, f, maxage=hours(99999999999999)) {
  basepath <- "Data/"
  mostRecent <- mostRecentTimestamp(storeName, basepath=basepath)
  f <- rlang::as_function(f)
  
  runAndArchive <- function() {
    data <- f()
    storeRDS(data, storeName, basepath)
    data
  }
    
  if (is.na(mostRecent)) 
    return(runAndArchive())

  if (mostRecent %--% now() < maxage)
    return(retrieveRDS(storeName, basepath))

  runAndArchive()
}
```

```{r, eval=F}
if (!require("devtools")) {
  install.packages("devtools")
}
devtools::install_github("weinbergerlab/ExcessILI")
```

us age
```{r}
#https://data.cdc.gov/NCHS/Weekly-counts-of-deaths-by-jurisdiction-and-age-gr/y5bj-9g5w/
#by jurisdiction of occurrence

us.age1 <- runIfExpired('nchs_age_state', ~read.csv('https://data.cdc.gov/api/views/y5bj-9g5w/rows.csv?accessType=DOWNLOAD'))


us.age1 <- us.age1[us.age1$Type=='Unweighted',]
us.age1 <- us.age1[,c("Jurisdiction" ,'Week.Ending.Date', 'Age.Group','Number.of.Deaths' )]
us.age1$Week.Ending.Date <- as.Date(us.age1$Week.Ending.Date, '%m/%d/%Y')

us.age1$agegroup2 <- NA
us.age1$agegroup2[us.age1$Age.Group %in% c('Under 25 years','25-44 years')] <- "00-44Y"
us.age1$agegroup2[us.age1$Age.Group %in% c('45-64 years')] <- "45-64Y"
us.age1$agegroup2[us.age1$Age.Group %in% c('65-74 years','75-84 years','85 years and older' )] <- "65+Y"

us.age1$state <- paste0(us.age1$Jurisdiction, us.age1$agegroup2)

us.age1 <- us.age1[us.age1$Jurisdiction %in% c("New York City", 'Arizona','California','Georgia','Florida', 'Illinois','Michigan','New Jersey','New York', 'Massachusetts','Ohio','United States','Texas','Virginia','Washington', 'Wisconsin','Louisiana'),]

us.age2 <- aggregate(us.age1[,c('Number.of.Deaths'), drop=F],
                     by=list('state'=us.age1$state,'week_end'=us.age1$Week.Ending.Date), FUN=sum, na.rm=T)
names(us.age2) <-c('state','week_end','all_cause')


```

U
```{r}
ds.comb <- us.age2
ds.comb$one <- 1
ds.comb <- ds.comb[ds.comb$week_end >= as.Date('2015-01-08') & ds.comb$week_end <= as.Date('2020-08-31') ,]

ds.comb <- ds.comb[order(ds.comb$state, ds.comb$week_end),]
```


## run the model
```{r}

mod1 <- excessCases(ds.comb, 
             statevar = "state",
             datevar = "week_end", 
             use.syndromes = c("all_cause"),
            extrapolation.date = as.Date("2020-03-01"), 
            sum.dates = as.Date("2020-03-01"),
            denom.var = "one",
            extend.epiyear =TRUE,
            time.res='week',
            model.type='poisson') 
```
 Extract output
```{r}
ds <- mod1
dates1 <-
  ds[[1]][[1]][[1]]$date
  
sum.obs.ac <-
    excessExtract(ds = ds,
                syndrome = 'all_cause',
                extract.quantity = "sum.obs")

sum.obs.ac2 <- apply(sum.obs.ac,2, sum)

denom.check <-
    excessExtract(ds = ds,
                syndrome = 'all_cause',
                extract.quantity = "denom")

dispersion <-
    excessExtract(ds = ds,
                syndrome = 'all_cause',
                extract.quantity = "disp")

##National data is created by summing state data
sum.pred.iter.ac <-    
  excessExtract(ds = ds,
                syndrome = 'all_cause',
                extract.quantity = "sum.pred.iter")

excess.grp <- matrix(NA, nrow=dim(sum.pred.iter.ac)[1], ncol=length(sum.obs.ac2))

for(i in 1:length(sum.obs.ac2)){
 excess.grp[,i] <-  sum.obs.ac2[i] - sum.pred.iter.ac[,i,1]
}
excess.grp.q <- t(apply(excess.grp,2, quantile, probs=c(0.025,0.5, 0.975)))
excess.grp.q <- cbind.data.frame('group'=dimnames(sum.obs.ac)[[2]],excess.grp.q)

ac.nat.obs <-    
  excessExtract(ds = ds,
                syndrome = 'all_cause',
                extract.quantity = "y")
ac.nat.obs <- ac.nat.obs[,dimnames(ac.nat.obs)[[2]]!='US',1]

pred.iter.ac <-    
  excessExtract(ds = ds,
                syndrome = 'all_cause',
                extract.quantity = "pred.iter")

pred.iter.ac2 <- array(pred.iter.ac,dim=c(length(dates1),10000,dim(pred.iter.ac)[2],1 ))

dimnames(pred.iter.ac2)[[3]] <- dimnames(pred.iter.ac)[[2]]

pred.ac.q <- apply(pred.iter.ac2, c(1,3), quantile, probs=c(0.025, 0.5, 0.975))


#excessN.iter <- sum.pred.iter.ac

```

## Summary of excess deaths March 1-Aug 29
```{r}
excess.grp.q.rd <- excess.grp.q
excess.grp.q.rd[,-1] <- apply(excess.grp.q[-1],2, function(x) round(x,-2))

outtab1 <- paste0(excess.grp.q.rd[,3], ' (', excess.grp.q.rd[,2],', ', excess.grp.q.rd[,4],')' )
outtab1 <- cbind.data.frame(excess.grp.q.rd[,1],outtab1)
htmlTable(outtab1)
```





## reshap to year*week
```{r}

mmw1 <- MMWRweek(ds.comb$week_end)
ds.comb <- cbind.data.frame(ds.comb, mmw1)

obs.m <- melt(ds.comb[,c('state', 'all_cause',"MMWRyear", "MMWRweek")], id.vars =c('state', "MMWRyear", "MMWRweek") )
obs.c <- acast(obs.m, state ~  MMWRyear ~ MMWRweek )

obs.c.out <- dcast(obs.m,   MMWRyear + MMWRweek ~state)
write.csv(obs.c.out, './Data/formatted_NCHS.csv' )
```


```{r}
col1 <- '#e41a1c'
col1.t <- '#e41a1c4D'
col2 <- '#377eb8'
col2.t <- '#377eb84D'
```

Georgia vs NYC
```{r, fig.width=3, fig.height=7}

par(mfrow=c(3,1))

groups.to.test<- list(
 
  c("Georgia00-44Y", "New York City00-44Y"),
  c('Georgia45-64Y', 'New York City45-64Y'),
  c('Georgia65+Y', 'New York City65+Y')
)

lab1 <- c('0-44y','45-64y','65+y')

denoms <- list(
  #c(9031213,8398748),
  c(1,1),
  c(1,1),
  c(1,1)
)

#Panel A

for(i in c(1:3)){
  yrange <- range( c(obs.c[groups.to.test[[i]][1],c('2020'),]/denoms[[i]][1]*100000, obs.c[groups.to.test[[i]][2],c('2020'),]/denoms[[i]][2]*100000), na.rm=T )
matplot(t(obs.c[groups.to.test[[i]][1],c('2017','2018','2019'),])/denoms[[i]][1]*100000, bty='l',type='l', col=col1.t, 
        ylim=c(0, yrange[2]),
        xlim=c(1,35),
        lty=1, ylab='Deaths', main=lab1[i])
points(obs.c[groups.to.test[[i]][1],c('2020'),]/denoms[[i]][1]*100000, type='l', col=col1, lty=1, lwd=2)

matplot(t(obs.c[groups.to.test[[i]][2],c('2017','2018','2019'),])/denoms[[i]][2]*100000, bty='l',type='l', col=col2.t,  lty=1,  add=T)
points(obs.c[groups.to.test[[i]][2],c('2020'),]/denoms[[i]][2]*100000, type='l', col=col2, lty=1, lwd=2)

}



```





